#pragma config(Motor,  port2,           RightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftDrive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftGoalLift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightGoalLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FirstLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           SecondLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RotateClaw,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  //put goal lift down
motor[LeftGoalLift] = motor[RightGoalLift] = -90;
wait1Msec(1700);
motor[LeftGoalLift] = motor[RightGoalLift] = 0;
wait1Msec(500);
//drive forward to pick up goal lift
motor[RightDrive] = motor[LeftDrive] = 90;
wait1Msec(1700);
motor[RightDrive] = motor[LeftDrive] = 0;
wait1Msec(500);
// put goal lift up
motor[RightGoalLift] = motor[LeftGoalLift] = 90;
wait1Msec(1700);
motor[RightGoalLift] = motor[LeftGoalLift] = 0;
wait1Msec(500);
//backup to clear cones
motor[RightDrive] = motor[LeftDrive] = -90;
wait1Msec(450);
motor[RightDrive] = motor[LeftDrive] = 0;
wait1Msec(500);
//turn to the left about 90 degrees
motor[RightDrive] = -90;
motor[LeftDrive] = 90;
wait1Msec(575);
motor[RightDrive] = motor[LeftDrive] = 0;
wait1Msec(500);
//drive forward for a tiny amount

//turn to the right about 90 degrees

//drive forward

//turn at a slight angle to the right

//drive forward

//put arm down

//backup

//turn to the right about 90 degrees

//drive forward a little bit

//turn to the left about 90 degrees

//put goal lift down

//drive forward

//put up goal lift

//turn to the right about 90 degrees

//drive forward a little bit

//turn to the left about 90 degrees

//drive forward a little bit

//turn to the left about 90 degrees

//drive forward

//turn slightly to the right

//drive forward

//put arm down

//backup

//turn to the right

//drive forward

// turn to the left about 90 degrees

//put goal lift down

//drive forward

//lift up goal lift

//back up

//turn to the right

//drive forward a little bit

//turn to the left

//drive forward

//put goal lift down

//backup

//turn about 180 to the right

//put arm down

//drive forward

//lift arm up

//turn to the right

//drive forward a little bit

//turn to the right

//drive forward

//turn to the left

//drive forward

//turn slightly to the right

//drive forwards

// put arm down

//backup

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
